version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: pg_orders
    restart: always
    environment:
      POSTGRES_USER: orders_dev
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbit_orders
    ports:
      - "5672:5672"   # application port
      - "15672:15672" # web management panel
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  pg_data:
